name: "Read the Docs Pull Request Preview"
author: "@readthedocs"
description: "Add a comment with links to the rendered version of the documentation on Read the Docs"

branding:
  color: gray
  icon: robot

inputs:
  project-slug:
    description: "Project's slug on Read the Docs"
    required: true
  project-language:
    description: "Project's language on Read the Docs"
    default: "en"
    required: false
  message-separator:
    description: "Text to separate the original body of the PR from the auto-inserted text"
    default: "----------"
    required: false
  message-template:
    description: "Template message to use for the PR body"
    default: ":books: :robot: Link to documentation preview: {docs-pr-index-url}\nSpecific pages:\n{docs-pr-file-links}"
  pretty-urls:
    description: "End links with 'page.html' or 'page/'"
    default: false
    required: false
  file-path:
    description: "Path where to check for file modifications"
    default: "docs/"
    required: false
  maximum-links:
    description: "Maximum numbers of links to put in the comment"
    default: 3
    required: false

runs:
  using: "composite"
  steps:
    - name: "Comment on Pull Request with Read the Docs' preview links"
      uses: actions/github-script@v6
      with:
        script: |
          var PR_NUMBER = context.issue.number;
          var RTD_PROJECT_SLUG = "${{ inputs.project-slug }}";
          var RTD_PROJECT_LANGUAGE = "${{ inputs.project-language }}";
          var RTD_URL = `https://${RTD_PROJECT_SLUG}--${PR_NUMBER}.org.readthedocs.build/${RTD_PROJECT_LANGUAGE}/${PR_NUMBER}/`;
          var MESSAGE_SEPARATOR = `${{ inputs.message-separator }}`;
          var MESSAGE_TEMPLATE = `${{ inputs.message-template }}`;
          var FILE_PATH = `${{ inputs.file-path }}`;

          const { data: pull } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });

          const {data: pull_files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });

          var body_message = `${MESSAGE_TEMPLATE.replace("{docs-pr-index-url}", RTD_URL)}`;
          var body_file_links = "";
          for (let file of pull_files) {
            if (file.filename.startsWith(FILE_PATH)) {
              url_path = file.filename.replace(FILE_PATH, "");
              body_file_links = body_message + "\n" + `* ${RTD_URL}${url_path}`;
            }
          }
          body_message = body_message.replace("{docs-pr-file-links}", body_file_links)

          var body = pull.body.split(/\r?\n/);
          body = body.slice(0, body.indexOf(MESSAGE_SEPARATOR));
          body = body.join("\n").trim() + "\n\n" + MESSAGE_SEPARATOR + "\n\n" + body_message;

          github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            body: body,
          });
