name: readthedocs/actions (fork)
on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: EliahKagan/readthedocs-actions/preview@experiment
        with:
          project-slug: "readthedocs-preview"
